name: CI/CD Pipeline for Render

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python (or Node.js)
        uses: actions/setup-python@v2  # Use actions/setup-node for Node.js
        with:
          python-version: '3.x'  # Change to 'node-version' for Node.js

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Adjust if using Node.js

      - name: Deploy to Render
        uses: render-examples/deploy-to-render@v1
        with:
          render-api-key: ${{ secrets.RENDER_API_KEY }}
          service-id: ${{ secrets.RENDER_SERVICE_ID }}

