name: CI/CD Pipeline for Render

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python (or Node.js)
        uses: actions/setup-python@v2  # Use actions/setup-node for Node.js
        with:
          python-version: '3.x'  # Change to 'node-version' for Node.js

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Adjust if using Node.js

      - name: Deploy to Render
        run: |
          curl -X POST "https://api.render.com/deploy/sync" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -d "serviceId=${{ secrets.RENDER_SERVICE_ID }}"

