name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the pipeline on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu for the build environment

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the version of Python to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install required packages

    - name: Run tests  # This is where you run your tests
      run: |
        python -m pip install pytest  # Install pytest for testing
        pytest  # Run the tests (make sure you have tests in your app)

    - name: Deploy to Render  # This is where you deploy your app
      run: |
        echo "Deploying to Render..."
        # Replace with the actual deployment command for your platform
        # For Render, you might use an API call or deploy commands
        curl -X POST -H "Authorization: Bearer $RENDER_API_KEY" \
          -d '{"serviceId": "your-service-id"}' \
          https://api.render.com/deploy  # Example Render deployment API
