 name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use a virtual environment for running tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the latest code

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Specify the Python version you're using

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install your app's dependencies

      - name: Run Tests
        run: |
          pytest  # Add tests to verify the functionality

  deploy:
    runs-on: ubuntu-latest
    needs: build  # This ensures the deploy job only runs after the build job is successful
    steps:
      - name: Deploy to Render
        run: |
          curl -fsSL https://render.com/deploy -d '{"branch": "main"}'  # Deploy to Render (you can use other platforms here)

